input_dir: "content" # I use "src" in some of my websites
layout_dir: "layouts" # can also be named "template", it"s up to you man.
static_dir: "static" # can be named "assets"
output_dir: "_build" # some folks like to use "public"

md_ext:
  - ".md"
  - ".mkd"
  - ".markdown"

defaults:
  layout: "post"
  title: "Genox Site"
  author: "Genox"
  author_link: "https://oxal.org/projects/genox/"

site:
  title: "Genox Site Title"
  google_analytics: "UA-GENOX"

manifest_file_name: "manfiest.json"
